export enum ErrorMessage {
    DEFAULT_ERROR = 'DEFAULT_ERROR',
    EXISTING_EMAIL = 'EXISTING_EMAIL',
    USER_NOT_FOUND ="USER_NOT_FOUND",
    EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
    PASSWORD_INCORRECT = "PASSWORD_INCORRECT",
    ACCOUNT_IS_ALREADY_VERIFIED = "ACCOUNT_IS_ALREADY_VERIFIED",
    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",
}