export enum SuccessMessage {
    CONNECTED_SUCCESS = 'CONNECTED_SUCCESS!',
    RESET_LINK_SENT = 'RESET_LINK_SENT',
    PASSWORD_UPDATED = 'PASSWORD_UPDATED',
    VERIFICATION_EMAIL_SENT = 'VERIFICATION_EMAIL_SENT ',
}